<html>
<head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-83731338-2"></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'UA-83731338-2');</script><title>20.23 The Class java.lang.ExceptionInInitializerError</title>
<META NAME=MS-HAID CONTENT="20_23">
<style>@import url(stylesheets/msdn_ie4.css);</style>
<link disabled rel="stylesheet" href="stylesheets/msdn_ie3.css"></head>
<body bgcolor=#ffffff>

<h1>20.23	 The Class java.lang.ExceptionInInitializerError</h1>
<a name="36092"></a>
<p>
<a name="36093"></a>
An <code>ExceptionInInitializerError</code> is thrown to indicate that an exception 
occurred during evaluation of a static initializer or the initializer for a <code>static</code> 
variable <a href="12_4_2.htm#44630">(&#167;12.4.2)</a>.
<p><pre><a name="35740"></a>public class <code><b>ExceptionInInitializerError
</b></code><a name="35764"></a>		extends RuntimeException {
<a name="35741"></a>	public <code><b>ExceptionInInitializerError</b></code>();
<a name="35774"></a>	public <code><b>ExceptionInInitializerError</b></code>(String s);
<a name="35776"></a>	public <code><b>ExceptionInInitializerError</b></code>(Throwable thrown);
<a name="35805"></a>	public Throwable <code><b>getException</b></code>();
<a name="35743"></a>}
</pre><p><a name="35744"></a>
<p><strong>20.23.1	</strong> <code>public ExceptionInInitializerError()</code>
<p>
<a name="35745"></a>
This constructor initializes a newly created <code>ExceptionInInitializerError</code> 
with <code>null</code> as its error message string and with a no saved throwable object.
<p><a name="35782"></a>
<p><strong>20.23.2	</strong> <code>public ExceptionInInitializerError(String s)</code>
<p>
<a name="35783"></a>
This constructor initializes a newly created <code>ExceptionInInitializerError</code> by 
saving a reference to the error message string <code>s</code> for later retrieval by the <code>getMessage</code> method <a href="20_22.htm#3275">(&#167;20.22.3)</a>. There is no saved throwable object.
<p><a name="35788"></a>
<p><strong>20.23.3	</strong> <code>public ExceptionInInitializerError(Throwable thrown)</code>
<p>
<a name="35789"></a>
This constructor initializes a newly created <code>ExceptionInInitializerError</code> by 
saving a reference to the <code>Throwable</code> object <code>thrown</code> for later retrieval by the 
<code>getException</code> method <a href="20_22.htm#3275">(&#167;20.22.3)</a>. The error message string is set to <code>null</code>.
<p><a name="35808"></a>
<p><strong>20.23.4	</strong> <code>public Throwable getException(Throwable thrown)</code>
<p>
<a name="35809"></a>
The saved throwable object of this <code>ExceptionInInitializerError</code> is returned; 
<code>null</code> is returned if this <code>ExceptionInInitializerError</code> has no saved throwable 
object.
<p><a name="35813"></a>

<p><a name="35806"></a>
<p>


<hr>
<p>
<br>
</font>
</body></html>
