<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML dir=ltr>
<HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-83731338-2"></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'UA-83731338-2');</script><title>Compiler Error J0101</title>
<style>@import url(stylesheets/msdn_ie4.css);</style>
<link disabled rel="stylesheet" href="stylesheets/msdn_ie3.css"></HEAD>
<BODY>

<h1><a name="vjmsgcompilererrorj0101"></a>Compiler Error J0101</h1>
<p class=dt>
<b>The type 'identifier' does not inherit from 'Throwable'</b></p>
<p>
The compiler detected an invalid class argument used as an argument in a <b>catch</b> statement. When using a <b>catch</b> statement to handle exceptions, you must define it with a class derived from <b>Throwable</b> as a parameter. Ensure that the class you defined for the <b>catch</b> statement is derived from <b>Throwable</b> and compile again.</p>
<p>
The following example illustrates this error:</p>
<pre><code>public class Simple {
 &nbsp; 
 &nbsp; public void method1() {
 &nbsp; 
 &nbsp;&nbsp;&nbsp;&nbsp; try {
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // do something meaningful
 &nbsp;&nbsp;&nbsp;&nbsp; } catch (String s) {
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // error: 'String' not a subclass
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // of 'Throwable'
 &nbsp;&nbsp;&nbsp;&nbsp; }
 &nbsp; }
}
</code></pre>
<p>
The following example illustrates the correct way to use the <b>catch</b> statement to trap exceptions:</p>
<pre><code>public class Simple{
 &nbsp; public void method1(int arg1){
 &nbsp;&nbsp;&nbsp;&nbsp; try{
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //do something here
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if (arg1 == 0)
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new myException(); //throw a valid exception object
 &nbsp;&nbsp;&nbsp;&nbsp; }
 &nbsp;&nbsp;&nbsp;&nbsp; catch(myException c){ //this is a valid exception object to catch
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //handle exception here
 &nbsp;&nbsp;&nbsp;&nbsp; }
 &nbsp; }
}
class myException extends Throwable{
 &nbsp; //class definition goes here
}
</code></pre>
</BODY>
</HTML>
